### ISSUE TITLE
NVCC error

### ISSUE THREAD

**Issue by kallivad** [6block/zkwork_aleo_worker#2]
running: "nvcc" "-ccbin=c++" "-Xcompiler" "-O3" "-Xcompiler" "-ffunction-sections" "-Xcompiler" "-fdata-sections" "-Xcompiler" "-fPIC" "-m64" "-I" "/home/kallivad/.cargo/registry/src/github.com-1ecc6299db9ec823/blst-0.3.10/blst/src" "-I" "/home/kallivad/.cargo/git/checkouts/sppark-766e0a6fee265121/48f6ac6" "-Xcompiler" "-Wall" "-Xcompiler" "-Wextra" "-g" "-arch=sm_70" "-maxrregcount=255" "-Xcompiler" "-Wno-unused-function" "-Xcompiler" "-Wno-subobject-linkage" "-DTAKE_RESPONSIBILITY_FOR_ERROR_MESSAGE" "-DFEATURE_BLS12_377" "-D__ADX__" "-o" "/home/kallivad/miners/zkwork_aleo_worker/target/release/build/snarkvm-cuda-2464e028f503cfea/out/cuda/snarkvm_api.o" "-c" "cuda/snarkvm_api.cu"
  cargo:warning=/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  cargo:warning=  435 |         function(_Functor&& __f)
  cargo:warning=      |                                                                                                                                                 ^ 
  cargo:warning=/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
  cargo:warning=/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  cargo:warning=  530 |         operator=(_Functor&& __f)
  cargo:warning=      |                                                                                                                                                  ^ 
  cargo:warning=/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
  exit status: 1

  --- stderr

  error occurred: Command "nvcc" "-ccbin=c++" "-Xcompiler" "-O3" "-Xcompiler" "-ffunction-sections" "-Xcompiler" "-fdata-sections" "-Xcompiler" "-fPIC" "-m64" "-I" "/home/kallivad/.cargo/registry/src/github.com-1ecc6299db9ec823/blst-0.3.10/blst/src" "-I" "/home/kallivad/.cargo/git/checkouts/sppark-766e0a6fee265121/48f6ac6" "-Xcompiler" "-Wall" "-Xcompiler" "-Wextra" "-g" "-arch=sm_70" "-maxrregcount=255" "-Xcompiler" "-Wno-unused-function" "-Xcompiler" "-Wno-subobject-linkage" "-DTAKE_RESPONSIBILITY_FOR_ERROR_MESSAGE" "-DFEATURE_BLS12_377" "-D__ADX__" "-o" "/home/kallivad/miners/zkwork_aleo_worker/target/release/build/snarkvm-cuda-2464e028f503cfea/out/cuda/snarkvm_api.o" "-c" "cuda/snarkvm_api.cu" with args "nvcc" did not execute successfully (status code exit status: 1).

**Comment by hairtail** [comment]
> running: "nvcc" "-ccbin=c++" "-Xcompiler" "-O3" "-Xcompiler" "-ffunction-sections" "-Xcompiler" "-fdata-sections" "-Xcompiler" "-fPIC" "-m64" "-I" "/home/kallivad/.cargo/registry/src/github.com-1ecc6299db9ec823/blst-0.3.10/blst/src" "-I" "/home/kallivad/.cargo/git/checkouts/sppark-766e0a6fee265121/48f6ac6" "-Xcompiler" "-Wall" "-Xcompiler" "-Wextra" "-g" "-arch=sm_70" "-maxrregcount=255" "-Xcompiler" "-Wno-unused-function" "-Xcompiler" "-Wno-subobject-linkage" "-DTAKE_RESPONSIBILITY_FOR_ERROR_MESSAGE" "-DFEATURE_BLS12_377" "-D__ADX__" "-o" "/home/kallivad/miners/zkwork_aleo_worker/target/release/build/snarkvm-cuda-2464e028f503cfea/out/cuda/snarkvm_api.o" "-c" "cuda/snarkvm_api.cu" cargo:warning=/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’: cargo:warning= 435 | function(_Functor&& __f) cargo:warning= | ^ cargo:warning=/usr/include/c++/11/bits/std_function.h:435:145: note: ‘_ArgTypes’ cargo:warning=/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’: cargo:warning= 530 | operator=(_Functor&& __f) cargo:warning= | ^ cargo:warning=/usr/include/c++/11/bits/std_function.h:530:146: note: ‘_ArgTypes’ exit status: 1
> 
> --- stderr
> 
> error occurred: Command "nvcc" "-ccbin=c++" "-Xcompiler" "-O3" "-Xcompiler" "-ffunction-sections" "-Xcompiler" "-fdata-sections" "-Xcompiler" "-fPIC" "-m64" "-I" "/home/kallivad/.cargo/registry/src/github.com-1ecc6299db9ec823/blst-0.3.10/blst/src" "-I" "/home/kallivad/.cargo/git/checkouts/sppark-766e0a6fee265121/48f6ac6" "-Xcompiler" "-Wall" "-Xcompiler" "-Wextra" "-g" "-arch=sm_70" "-maxrregcount=255" "-Xcompiler" "-Wno-unused-function" "-Xcompiler" "-Wno-subobject-linkage" "-DTAKE_RESPONSIBILITY_FOR_ERROR_MESSAGE" "-DFEATURE_BLS12_377" "-D__ADX__" "-o" "/home/kallivad/miners/zkwork_aleo_worker/target/release/build/snarkvm-cuda-2464e028f503cfea/out/cuda/snarkvm_api.o" "-c" "cuda/snarkvm_api.cu" with args "nvcc" did not execute successfully (status code exit status: 1).

cuda toolkit needed for now. install cuda first, then try again.
