### ISSUE TITLE
build cuda fail

### ISSUE THREAD

**Issue by bangdracaena** [6block/zkwork_aleo_worker#3]
cargo build --release --features cuda
    Updating git repository `https://github.com/AleoHQ/snarkVM.git`
error: failed to load source for dependency `snarkvm`

Caused by:
  Unable to update https://github.com/AleoHQ/snarkVM.git?branch=feat/snarkvm-cuda#dafd8cc0

Caused by:
  object not found - no match for id (dafd8cc08196043c7eca11525786b978ce3f8606); class=Odb (9); code=NotFound (-3)

**Comment by Matthewthefaker** [comment]
same issue, all that I can found is this bug appears on corrupted registry files in cargo. But I don't really have one

**Comment by Pegasus-starry** [comment]
@Matthewthefaker @bangdracaena Please use the latest code and try again.    
And if meet some other issues such as :  cargo:warning=cuda/snarkvm.cu:29:10: fatal error: ntt/ntt.cuh: No such file or directory
Try to copy ntt/*
folder https://github.com/supranational/sppark/tree/main/ntt to /root/.cargo/registry/src/github.com-1ecc6299db9ec823/sppark-0.1.3/sppark/  (https://github.com/AleoHQ/snarkVM/pull/1288#issuecomment-1364311212)
